---
- name: basic acas configuration
  hosts: all
  strategy: free
  become: yes
  tasks:
    - name: Wait for vm/nic to come up
      wait_for_connection:
        delay: 30
        timeout: 300
    - name: show os family
      debug:
        msg: Host OS = {{ ansible_os_family }}
    - name: check/install for updates after deployment
      when: ansible_facts['os_family'] == 'Redhat'
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: remove any un-needed files after system updates
      ansible.builtin.dnf:
        autoremove: yes
    - name: reboot after updates
      ansible.builtin.reboot:
        reboot_timeout: 3600
    - name: run high level STIG for RHEL8 (v1 r13)
      import_role:
        name: rhel8STIG
    - name: reboot after STIG
      ansible.builtin.reboot:
        reboot_timeout: 3600
