---
- name: configure security center host
  hosts: all
  become: yes
  tasks:
    - name: copy sc install/rpm to host
      ansible.builtin.copy:
        src: ../tenable_files_repo/CM-296116_SecurityCenter-6.1.1-el8.x86_64.rpm
        dest: /home/acas
        owner: acas
        group: acas
        mode: '0700'
    - name: install securityCenter from local repo
      ansible.builtin.dnf:
        name: /home/acas/CM-296116_SecurityCenter-6.1.1-el8.x86_64.rpm
        disable_gpg_check: true
        state: present
    - name: add firewall rule for security center
      ansible.posix.firewalld:
        service: https
        permanent: true
        state: enabled
    - name: restart firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: restarted

